"""Tests for the booking agent end to end, on scripted model responses."""

from __future__ import annotations

import pytest

from agents.calendar_booking.agent import CalendarBookingAgent
from agents.calendar_booking.fixtures import (
    DANA,
    NINA,
    ORGANISER,
    REFERENCE_NOW,
    berlin,
)
from agents.calendar_booking.models import (
    BookingRequest,
    BusyBlock,
    MeetingProposal,
    SchedulingPolicy,
    TimeSlot,
)
from agents.calendar_booking.providers import MockCalendar
from agents.calendar_booking.scripted import REQUESTS, provider_for
from core.config import Settings


def settings() -> Settings:
    return Settings(trace_enabled=False)


def build(scenario: str, calendar: MockCalendar | None = None):
    calendar = calendar or MockCalendar()
    agent = CalendarBookingAgent(
        provider=provider_for(scenario),
        calendar=calendar,
        organiser=ORGANISER,
        settings=settings(),
        now=REFERENCE_NOW,
    )
    return agent, calendar


# --- Proposing ----------------------------------------------------------


def test_a_request_is_parsed_into_a_structured_booking():
    agent, _ = build("internal")
    proposal = agent.propose(REQUESTS["internal"])

    assert proposal.request.duration_minutes == 45
    assert proposal.request.attendee_emails == [NINA.email]
    assert proposal.request.title


def test_openings_are_offered():
    agent, _ = build("internal")
    proposal = agent.propose(REQUESTS["internal"])

    assert proposal.has_options
    assert len(proposal.slots) <= SchedulingPolicy().max_suggestions


def test_every_offered_slot_is_inside_everyones_working_hours():
    agent, _ = build("transatlantic")
    proposal = agent.propose(REQUESTS["transatlantic"])

    assert proposal.has_options
    for slot in proposal.slots:
        assert ORGANISER.working_hours.covers(slot.start, slot.end)
        assert DANA.working_hours.covers(slot.start, slot.end)


def test_every_offered_slot_has_the_requested_duration():
    agent, _ = build("internal")
    proposal = agent.propose(REQUESTS["internal"])

    assert all(slot.duration_minutes == 45 for slot in proposal.slots)


def test_offered_slots_respect_the_minimum_notice():
    agent, _ = build("internal")
    proposal = agent.propose(REQUESTS["internal"])

    earliest_allowed = REFERENCE_NOW.timestamp() + SchedulingPolicy().min_notice_hours * 3600
    assert all(slot.start.timestamp() >= earliest_allowed for slot in proposal.slots)


def test_the_models_wording_is_used_when_there_are_options():
    agent, _ = build("internal")
    proposal = agent.propose(REQUESTS["internal"])

    assert "Nina" in proposal.message


def test_an_impossible_request_yields_no_slots_and_a_deterministic_message():
    # The organiser is at an offsite all day on Wednesday the 11th, and the
    # request insists on that date.
    agent, _ = build("impossible")
    proposal = agent.propose(REQUESTS["impossible"])

    assert proposal.slots == []
    # The scripted model text is discarded — the fallback is generated by code,
    # so an empty result can never be described as a set of options.
    assert "could not find" in proposal.message


# --- Booking ------------------------------------------------------------


def test_booking_creates_an_event():
    agent, calendar = build("internal")
    proposal = agent.propose(REQUESTS["internal"])
    result = agent.book(proposal, 0)

    assert result.booked is True
    assert result.event_id
    assert len(calendar.created) == 1
    assert calendar.created[0].slot == proposal.slots[0]


def test_the_organiser_is_always_an_attendee():
    agent, calendar = build("internal")
    proposal = agent.propose(REQUESTS["internal"])
    agent.book(proposal, 0)

    assert ORGANISER.email in calendar.created[0].attendee_emails
    assert NINA.email in calendar.created[0].attendee_emails


def test_the_confirmation_names_the_time_in_every_attendee_time_zone():
    agent, _ = build("transatlantic")
    proposal = agent.propose(REQUESTS["transatlantic"])
    result = agent.book(proposal, 0)

    assert result.booked is True
    assert "CET" in result.confirmation
    assert "EST" in result.confirmation or "EDT" in result.confirmation


def test_a_slot_taken_between_proposing_and_booking_is_refused():
    agent, calendar = build("internal")
    proposal = agent.propose(REQUESTS["internal"])

    # Someone else books the same time in the meantime.
    slot = proposal.slots[0]
    calendar.create_event(title="Something else", slot=slot, attendee_emails=[ORGANISER.email])

    result = agent.book(proposal, 0)
    assert result.booked is False
    assert "Something else" in result.failure_reason


def test_booking_an_index_that_was_not_offered_is_refused():
    agent, calendar = build("internal")
    proposal = agent.propose(REQUESTS["internal"])

    result = agent.book(proposal, 99)
    assert result.booked is False
    assert "outside" in result.failure_reason
    assert calendar.created == []


def test_booking_with_nothing_proposed_is_refused():
    agent, _ = build("impossible")
    proposal = agent.propose(REQUESTS["impossible"])

    result = agent.book(proposal, 0)
    assert result.booked is False
    assert "no slots" in result.failure_reason


def test_booking_does_not_call_the_model():
    # The provider is scripted with exactly the two responses `propose` needs.
    # If `book` asked for another, the mock would raise instead of silently
    # continuing — booking must not depend on a model.
    agent, _ = build("internal")
    proposal = agent.propose(REQUESTS["internal"])

    result = agent.book(proposal, 0)
    assert result.booked is True


# --- Attendee resolution ------------------------------------------------


def test_unknown_attendees_are_skipped_rather_than_guessed():
    calendar = MockCalendar()
    agent = CalendarBookingAgent(
        provider=provider_for("internal"),
        calendar=calendar,
        organiser=ORGANISER,
        settings=settings(),
        now=REFERENCE_NOW,
    )
    request = BookingRequest(
        title="Test",
        duration_minutes=30,
        attendee_emails=["nobody@nowhere.example"],
    )
    slots = agent._find(request)

    # Falls back to the organiser alone. Inventing working hours for an unknown
    # address would produce confidently wrong times.
    assert slots
    assert all(ORGANISER.working_hours.covers(s.start, s.end) for s in slots)


def test_the_organiser_is_not_duplicated_when_listed_as_an_attendee():
    _, calendar = build("internal")
    agent = CalendarBookingAgent(
        provider=provider_for("internal"),
        calendar=calendar,
        organiser=ORGANISER,
        settings=settings(),
        now=REFERENCE_NOW,
    )
    resolved = agent._attendees([ORGANISER.email, NINA.email])

    assert [a.email for a in resolved] == [ORGANISER.email, NINA.email]


# --- Calendar provider --------------------------------------------------


def test_the_mock_calendar_remembers_what_it_booked():
    calendar = MockCalendar()
    before = calendar.busy_blocks(ORGANISER.email, berlin(12, 0), berlin(13, 0))

    calendar.create_event(
        title="New thing",
        slot=TimeSlot(start=berlin(12, 10), end=berlin(12, 11)),
        attendee_emails=[ORGANISER.email],
    )
    after = calendar.busy_blocks(ORGANISER.email, berlin(12, 0), berlin(13, 0))

    assert len(after) == len(before) + 1


def test_busy_blocks_are_filtered_to_the_requested_window():
    calendar = MockCalendar(
        calendars={
            ORGANISER.email: [
                BusyBlock(start=berlin(5, 9), end=berlin(5, 10), title="In window"),
                BusyBlock(start=berlin(20, 9), end=berlin(20, 10), title="Out of window"),
            ]
        }
    )
    blocks = calendar.busy_blocks(ORGANISER.email, berlin(5, 0), berlin(6, 0))

    assert [b.title for b in blocks] == ["In window"]


def test_an_unknown_email_resolves_to_nothing():
    assert MockCalendar().resolve_attendee("stranger@example.com") is None


def test_proposal_without_slots_reports_no_options():
    proposal = MeetingProposal(
        request=BookingRequest(title="x", duration_minutes=30, attendee_emails=[]),
        slots=[],
    )
    assert proposal.has_options is False


def test_scripted_scenarios_all_exist():
    for scenario in REQUESTS:
        assert provider_for(scenario) is not None

    with pytest.raises(KeyError):
        provider_for("no-such-scenario")
